import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from '../components/banner'
import heroImage from '../public/images/hero-image.png'

export default function Home() {
  const handleOnButtonClick = () => {
    console.log('button click')
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        {/* <h1 className={styles.title}>Coffee Connoisseur</h1> */}
        <Banner
          buttonText='View stores nearby'
          handleOnClick={handleOnButtonClick}
        />
        <div className={styles.heroImage}>
          <Image src={heroImage} width={700} height={400} alt='hero image' />
        </div>
      </main>
    </div>
  )
}
